### ISSUE TITLE
Thor dependency for rails 4

### ISSUE THREAD

**Issue by websymphony** [northwestern-fsm/bcdatabase#24]
Currently this gem is locked to Thor version v.0.14, but Rails 4 has minimum dependency on Thor v.0.18.1.

Can we update this dependency?

**Comment by rsutphin** [comment]
The current dependency is on thor `"~> 0.14"`. This [is equivalent to](http://guides.rubygems.org/patterns/#pessimistic-version-constraint) `[">= 0.14", "< 1.0"]`, which includes `0.18.1`. This has been the case for bcdatabase since v1.2.3.

If you are having issues upgrading to Rails 4, perhaps you have bcdatabase locked to an earlier version. Or perhaps there's another version conflict which is resulting in bundler pulling in an older version of bcdatabase.

**Comment by websymphony** [comment]
Thanks Rhett. You were right, there was another conflict that was pulling older version.
